# Generated by Django 4.2.11 on 2024-11-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='category',
            field=models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('internet', 'Internet Fixer'), ('cleaner', 'Cleaner'), ('delivery', 'Delivery')], max_length=12),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('internet', 'Internet Fixer'), ('cleaner', 'Cleaner'), ('delivery', 'Delivery')], max_length=12),
        ),
    ]
