# Generated by Django 4.2.11 on 2024-11-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='discription',
            field=models.TextField(max_length=800),
        ),
    ]
