# Generated by Django 5.0 on 2023-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='id',
        ),
        migrations.AlterField(
            model_name='musician',
            name='email',
            field=models.EmailField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
