# Generated by Django 4.2.15 on 2024-09-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service_title',
        ),
    ]
