# Generated by Django 4.2.15 on 2024-09-03 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_buyerprofile_account_type_and_more'),
        ('services', '0002_rename_name_service_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.sellerprofile'),
            preserve_default=False,
        ),
    ]
