# Generated by Django 4.2.15 on 2024-09-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('internet', 'Internet Fixer'), ('cleaner', 'House Cleaner')], max_length=50),
        ),
    ]
