# Generated by Django 4.2.15 on 2024-09-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_buyerprofile_account_type_and_more'),
        ('services', '0004_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sellerprofile'),
        ),
    ]
