# Generated by Django 4.2.11 on 2024-11-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='ll', upload_to='static/'),
            preserve_default=False,
        ),
    ]
