# Generated by Django 4.2.15 on 2024-08-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='degisnation',
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default=11, upload_to='doctor/media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='AvailableTime',
            field=models.ManyToManyField(to='doctor.availabletime'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Designation',
            field=models.ManyToManyField(to='doctor.designation'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Specialization',
            field=models.ManyToManyField(to='doctor.specialization'),
        ),
    ]
