# Generated by Django 4.2.15 on 2024-08-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
    ]
