# Generated by Django 4.2.15 on 2024-09-02 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('bio', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('account_type', models.CharField(default='buyer_account', max_length=50)),
                ('total_bought', models.IntegerField()),
                ('total_spent', models.IntegerField()),
            ],
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('account_type', models.CharField(default='seller_account', max_length=50)),
                ('total_jobs', models.IntegerField()),
            ],
            bases=('accounts.profile',),
        ),
    ]
