# Generated by Django 4.2.15 on 2024-09-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='total_bought',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='total_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
