# Generated by Django 4.2.15 on 2024-09-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_buyerprofile_total_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='account_type',
            field=models.CharField(default='buyer_account', max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='account_type',
            field=models.CharField(default='seller_account', max_length=20),
        ),
    ]
