# Generated by Django 5.0 on 2023-12-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=20)),
                ('taskDescription', models.CharField(max_length=80)),
                ('is_completed', models.BooleanField(default=False)),
                ('assign_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
