# Generated by Django 5.0 on 2023-12-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_categorie_tasks'),
        ('tasklist', '0002_alter_tasklist_assign_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='categorie',
            field=models.ManyToManyField(to='categories.categorie'),
        ),
    ]
