# Generated by Django 4.2.15 on 2024-08-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_delete_review'),
        ('patient', '0002_alter_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateing', models.CharField(choices=[('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], max_length=12)),
                ('text', models.TextField(max_length=50)),
                ('doctor_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_review', to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paitent_review', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('symptoms', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('doctor', models.ManyToManyField(related_name='doctor_apointment', to='doctor.doctor')),
                ('patient', models.ManyToManyField(related_name='patient_apointment', to='patient.patient')),
            ],
        ),
    ]
