# Generated by Django 5.0 on 2023-12-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tasklist', '0002_alter_tasklist_assign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='tasks',
            field=models.ManyToManyField(related_name='categories', to='tasklist.tasklist'),
        ),
    ]
