# Generated by Django 4.2.15 on 2024-08-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to=None)),
                ('price', models.IntegerField(max_length=20)),
            ],
        ),
    ]
