# Generated by Django 4.2.15 on 2024-08-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
