# Generated by Django 5.0 on 2024-01-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_image',
            field=models.ImageField(upload_to='cars/media/upload'),
        ),
    ]
