# Generated by Django 5.0 on 2024-01-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
