# Generated by Django 5.0 on 2023-12-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='assign_date',
            field=models.DateField(),
        ),
    ]
