# Generated by Django 4.2.11 on 2024-11-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart_category_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.cart'),
        ),
    ]
