# Generated by Django 4.2.11 on 2024-11-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_ordered_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
    ]
