# Generated by Django 4.2.15 on 2024-09-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_category_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='address',
        ),
    ]
