# Generated by Django 4.2.11 on 2024-11-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_ordered_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
            preserve_default=False,
        ),
    ]
