# Generated by Django 4.2.15 on 2024-08-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_alter_books_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCategory',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='categories',
            new_name='category',
        ),
    ]
