# Generated by Django 4.2.15 on 2024-08-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_categories_slug_alter_books_image_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='Books/media/'),
        ),
    ]
