# Generated by Django 5.0 on 2023-12-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasklist', '0002_alter_tasklist_assign_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('tasks', models.ManyToManyField(to='tasklist.tasklist')),
            ],
        ),
    ]
