# Generated by Django 5.0 on 2023-12-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_categorie_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='tasks',
        ),
    ]
